/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.carrotsearch.gradle.randomizedtesting;

import org.gradle.api.Project;
import org.gradle.api.plugins.JavaPlugin;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.Assert;
import org.junit.Test;

/** A simple unit test. */
public class RandomizedTestingPluginTest {
  @Test
  public void extensionsAdded() {
    Project project = ProjectBuilder.builder().build();

    project.getPlugins().apply(JavaPlugin.class);
    project.getPlugins().apply("com.carrotsearch.gradle.randomizedtesting");

    RandomizedTestingExtension ext =
        project.getExtensions().findByType(RandomizedTestingExtension.class);
    Assert.assertNotNull(ext);

    RootProjectGlobals globals = project.getExtensions().findByType(RootProjectGlobals.class);
    Assert.assertNotNull(globals);
  }
}
